language: scala
sudo: false
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0
jdk:
  - openjdk8
script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}" test
  - git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
